name: climate-analysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - netcdf4
  - scipy
  - matplotlib
  - cdo 
  - cartopy
  - scikit-learn
  - jupyterlab
