name: binder-env
channels:
  - conda-forge
dependencies:
  - python
  - climlab
  - metpy
  - cartopy
  - netCDF4
  - cdo
  - cdsapi
  - nbgitpuller
  - sphinx-gallery
  - pandas
  - matplotlib
  - jupyterlab
